import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';

export interface ApiKey {
  id: string;
  key_name: string;
  api_key: string;
  is_active: boolean;
  created_by: string | null;
  permissions: string[];
  rate_limit: number;
  last_used: string | null;
  expires_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ApiLog {
  id: string;
  api_key_id: string;
  endpoint: string;
  method: string;
  request_data: any;
  response_status: number;
  response_data: any;
  ip_address: string | null;
  user_agent: string | null;
  created_at: string;
}

export const useApiKeys = () => {
  const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
  const [apiLogs, setApiLogs] = useState<ApiLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchApiKeys = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('api_keys')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setApiKeys(data || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error fetching API keys');
    } finally {
      setLoading(false);
    }
  };

  const fetchApiLogs = async (apiKeyId?: string) => {
    try {
      let query = supabase
        .from('api_logs')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(100);

      if (apiKeyId) {
        query = query.eq('api_key_id', apiKeyId);
      }

      const { data, error } = await query;

      if (error) throw error;
      setApiLogs(data || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error fetching API logs');
    }
  };

  const createApiKey = async (keyData: {
    key_name: string;
    permissions?: string[];
    rate_limit?: number;
    expires_at?: string;
  }) => {
    try {
      const { data, error } = await supabase
        .from('api_keys')
        .insert([{
          ...keyData,
          api_key: '', // Will be auto-generated by trigger
          expires_at: keyData.expires_at || null
        }])
        .select()
        .single();

      if (error) throw error;
      await fetchApiKeys();
      return { data, error: null };
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Error creating API key';
      setError(errorMessage);
      return { data: null, error: errorMessage };
    }
  };

  const updateApiKey = async (id: string, updates: Partial<ApiKey>) => {
    try {
      const { data, error } = await supabase
        .from('api_keys')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      await fetchApiKeys();
      return { data, error: null };
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Error updating API key';
      setError(errorMessage);
      return { data: null, error: errorMessage };
    }
  };

  const deleteApiKey = async (id: string) => {
    try {
      const { error } = await supabase
        .from('api_keys')
        .delete()
        .eq('id', id);

      if (error) throw error;
      await fetchApiKeys();
      return { error: null };
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Error deleting API key';
      setError(errorMessage);
      return { error: errorMessage };
    }
  };

  const toggleApiKey = async (id: string, isActive: boolean) => {
    return updateApiKey(id, { is_active: isActive });
  };

  useEffect(() => {
    fetchApiKeys();
  }, []);

  return {
    apiKeys,
    apiLogs,
    loading,
    error,
    fetchApiKeys,
    fetchApiLogs,
    createApiKey,
    updateApiKey,
    deleteApiKey,
    toggleApiKey
  };
};