// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hizfxcxcegckhswmsaui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpemZ4Y3hjZWdja2hzd21zYXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODgyNTQsImV4cCI6MjA3Mjc2NDI1NH0.0tO0vcgdkOdKeE2bRZg658tNT7YY4uU0VH4Km3pUbWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});